CREATE PROC PROC_UPDATE_BANAN
( @MABAN VARCHAR(10), @TANG VARCHAR(3), @KIEUBAN nVARCHAR(50), @SOGHE SMALLINT, @MAPYC VARCHAR(10))
AS
BEGIN 
	UPDATE BanAn
	SET MaBan = @MABAN, Tang = @TANG, Kieuban = @KIEUBAN, SoGhe = @SOGHE, MaPYC = @MAPYC
	WHERE MaBan = @MABAN
END

CREATE PROC PROC_DELETE_BANAN
( @MABAN VARCHAR(10))
AS
BEGIN
	DELETE FROM BanAn
	WHERE MaBan = @MABAN
END

CREATE PROC PROC_INSERT_BANAN
( @MABAN VARCHAR(10), @TANG VARCHAR(3), @KIEUBAN nVARCHAR(50), @SOGHE SMALLINT, @MAPYC VARCHAR(10))
AS
BEGIN
	INSERT BanAn(MaBan,Tang,Kieuban,SoGhe,MaPYC)
	VALUES (@MABAN,@TANG,@KIEUBAN,@SOGHE,@MAPYC)
END


CREATE PROC PROC_INSERT_THUCPHAM
( @MATP VARCHAR(10), @TENTP NVARCHAR(50), @DVT NVARCHAR(10),@SOLUONGTON INT,@GIABAN INT)
AS
BEGIN
	INSERT ThucPham(MaTP,TenTP,DVTinhTP,SoLuongTon,giaban)
	VALUES (@MATP ,@TENTP ,@DVT ,@SOLUONGTON ,@GIABAN)
END

CREATE PROC PROC_DELETE_THUCPHAM
( @MATP VARCHAR(10))
AS
BEGIN
DELETE FROM ThucPham
WHERE MaTP = @MATP
DELETE FROM ChiTietThucPham
WHERE MaTP = @MATP
END
