CREATE PROC PROC_UPDATE_BANAN
( @MABAN VARCHAR(10), @TANG VARCHAR(3), @KIEUBAN nVARCHAR(50), @SOGHE SMALLINT, @MAPYC VARCHAR(10))
AS
BEGIN 
	UPDATE BanAn
	SET MaBan = @MABAN, Tang = @TANG, Kieuban = @KIEUBAN, SoGhe = @SOGHE, MaPYC = @MAPYC
	WHERE MaBan = @MABAN
END

CREATE PROC PROC_DELETE_BANAN
( @MABAN VARCHAR(10))
AS
BEGIN
	DELETE FROM BanAn
	WHERE MaBan = @MABAN
END

CREATE PROC PROC_INSERT_BANAN
( @MABAN VARCHAR(10), @TANG VARCHAR(3), @KIEUBAN nVARCHAR(50), @SOGHE SMALLINT, @MAPYC VARCHAR(10))
AS
BEGIN
	INSERT BanAn(MaBan,Tang,Kieuban,SoGhe,MaPYC)
	VALUES (@MABAN,@TANG,@KIEUBAN,@SOGHE,@MAPYC)
END


CREATE PROC PROC_INSERT_THUCPHAM
( @MATP VARCHAR(10), @TENTP NVARCHAR(50), @DVT NVARCHAR(10),@SOLUONGTON INT,@GIABAN INT)
AS
BEGIN
	INSERT ThucPham(MaTP,TenTP,DVTinhTP,SoLuongTon,giaban)
	VALUES (@MATP ,@TENTP ,@DVT ,@SOLUONGTON ,@GIABAN)
END

CREATE PROC PROC_DELETE_THUCPHAM
( @MATP VARCHAR(10))
AS
BEGIN
DELETE FROM ThucPham
WHERE MaTP = @MATP
DELETE FROM ChiTietThucPham
WHERE MaTP = @MATP
END

CREATE PROC PRO_INSERT_NCC
( @MANCC VARCHAR(10), @TENNCC NVARCHAR(50),@DIACHI NVARCHAR(10),@SDT INT)
AS
BEGIN
	INSERT NhaCungCap(MaNCC,TenNCC,DiaChi,SDT)
	VALUES (@MANCC,@TENNCC,@DIACHI,@SDT)
END

CREATE PROC PROC_DELETE_NCC
(@MANCC VARCHAR(10))
AS
BEGIN
DELETE FROM NhaCungCap
WHERE MaNCC = @MANCC
DELETE FROM PhieuNhapThucPham
WHERE MaNCC = @MANCC
END

CREATE PROC PROC_UPDATE_NCC
( @MANCC VARCHAR(10), @TENNCC NVARCHAR(50),@DIACHI NVARCHAR(10),@SDT INT)
AS
BEGIN
UPDATE NhaCungCap
SET MaNCC = @MANCC,TenNCC = @TENNCC, DiaChi = @DIACHI, SDT = @SDT
WHERE MaNCC = @MANCC
END

CREATE PROC PROC_INSERT_CHINHANH
(@MACN VARCHAR(10),@TENCN NVARCHAR(50),@DIACHICN NVARCHAR(100))
AS
BEGIN
	INSERT ChiNhanh(MaCN,TenCN,DiaChiCN)
	VALUES (@MACN,@TENCN,@DIACHICN)
END

CREATE PROC PROC_UPDATE_CHINHANH
(@MACN VARCHAR(10),@TENCN NVARCHAR(50),@DIACHICN NVARCHAR(100))
AS
BEGIN
UPDATE ChiNhanh
SET MaCN = @MACN, TenCN = @TENCN, DiaChiCN = @DIACHICN
WHERE MaCN = @MACN
END

CREATE PROC PROC_DELETE_CHINHANH
(@MACN VARCHAR(10))
AS
BEGIN
DELETE FROM ChiNhanh
WHERE MaCN = @MACN
DELETE FROM NhanVien
WHERE MaCN = @MACN
END

CREATE PROC PROC_INSERT_KHACHHANG
(@MAKH VARCHAR(10), @TENKH NVARCHAR(50), @DIACHIKH NVARCHAR(100),@SDT TEXT)
AS
BEGIN
INSERT KhachHang(MaKH,TenKH,DiaChiKH,SDT)
VALUES (@MAKH,@TENKH,@DIACHIKH,@SDT)
END

CREATE PROC PROC_DELETE_KHACHHANG
(@MAKH VARCHAR(10))
AS
BEGIN
DELETE FROM KhachHang
WHERE MaKH = @MAKH
DELETE FROM HoaDon
WHERE MaKH = @MAKH
END

CREATE PROC PROC_UPDATE_KHACHHANG
(@MAKH VARCHAR(10), @TENKH NVARCHAR(50), @DIACHIKH NVARCHAR(100),@SDT TEXT)
AS
BEGIN
UPDATE KhachHang
SET MaKH = @MAKH, TenKH = @TENKH,DiaChiKH = @DIACHIKH,SDT = @SDT
WHERE MaKH = @MAKH
END



